name: SQLFluff

on: [push]

jobs:
  sql-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
            python-version: "3.8"
      - name: Update and install SQLFluff dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install sqlfluff
      - name: Lint models
        run: sqlfluff lint $(git ls-files '*.sql') --dialect sqlite